CREATE TABLE IF NOT EXISTS Inventory (
    EntryID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title VARCHAR(255) NOT NULL,
    Author VARCHAR(255) NOT NULL,
    Genre VARCHAR(100),
    PublicationDate DATE NOT NULL,
    ISBN VARCHAR(13) UNIQUE NOT NULL
);